#!/run/current-system/sw/bin/zsh

echo "Content-Type: text/html; charset=utf-8

<pre>
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
"

for i in finhdd1 gerssd1 scale{21..23}; do
	echo $i
	timeout 7s ssh at@$i "ps auxw | grep -P '[y]outube_dl'" 2>&1 | sed -r 's/ --proxy \S+ / /g'
done
